# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doorbell.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'doorbell.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64oorbell.proto\x12\rding.doorbell\"i\n\x0bScanRequest\x12\x12\n\nqr_code_id\x18\x01 \x01(\t\x12\x19\n\x11scanner_device_id\x18\x02 \x01(\t\x12\x18\n\x10scanner_location\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"[\n\x0cScanResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x15\n\rdoor_owner_id\x18\x04 \x01(\t\"\xc0\x01\n\x0cNotification\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t\x12\x15\n\rdoor_owner_id\x18\x02 \x01(\t\x12\x19\n\x11scanner_device_id\x18\x03 \x01(\t\x12-\n\x04type\x18\x04 \x01(\x0e\x32\x1f.ding.doorbell.NotificationType\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x12\n\nsession_id\x18\x07 \x01(\t\"\x85\x01\n\x0c\x44ingResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x15\n\rdoor_owner_id\x18\x02 \x01(\t\x12\x32\n\rresponse_type\x18\x03 \x01(\x0e\x32\x1b.ding.doorbell.ResponseType\x12\x16\n\x0e\x63ustom_message\x18\x04 \x01(\t\"L\n\x0eResponseResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10video_session_id\x18\x03 \x01(\t\"B\n\x13NotificationRequest\x12\x15\n\rdoor_owner_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65vice_token\x18\x02 \x01(\t*\\\n\x10NotificationType\x12\x10\n\x0c\x44ING_REQUEST\x10\x00\x12\x10\n\x0c\x44ING_TIMEOUT\x10\x01\x12\x11\n\rDING_ACCEPTED\x10\x02\x12\x11\n\rDING_REJECTED\x10\x03*<\n\x0cResponseType\x12\n\n\x06\x41\x43\x43\x45PT\x10\x00\x12\n\n\x06REJECT\x10\x01\x12\x08\n\x04\x42USY\x10\x02\x12\n\n\x06\x43USTOM\x10\x03\x32\xfe\x01\n\x0f\x44oorbellService\x12\x45\n\nScanQRCode\x12\x1a.ding.doorbell.ScanRequest\x1a\x1b.ding.doorbell.ScanResponse\x12W\n\x12NotificationStream\x12\".ding.doorbell.NotificationRequest\x1a\x1b.ding.doorbell.Notification0\x01\x12K\n\rRespondToDing\x12\x1b.ding.doorbell.DingResponse\x1a\x1d.ding.doorbell.ResponseResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doorbell_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONTYPE']._serialized_start=710
  _globals['_NOTIFICATIONTYPE']._serialized_end=802
  _globals['_RESPONSETYPE']._serialized_start=804
  _globals['_RESPONSETYPE']._serialized_end=864
  _globals['_SCANREQUEST']._serialized_start=33
  _globals['_SCANREQUEST']._serialized_end=138
  _globals['_SCANRESPONSE']._serialized_start=140
  _globals['_SCANRESPONSE']._serialized_end=231
  _globals['_NOTIFICATION']._serialized_start=234
  _globals['_NOTIFICATION']._serialized_end=426
  _globals['_DINGRESPONSE']._serialized_start=429
  _globals['_DINGRESPONSE']._serialized_end=562
  _globals['_RESPONSERESULT']._serialized_start=564
  _globals['_RESPONSERESULT']._serialized_end=640
  _globals['_NOTIFICATIONREQUEST']._serialized_start=642
  _globals['_NOTIFICATIONREQUEST']._serialized_end=708
  _globals['_DOORBELLSERVICE']._serialized_start=867
  _globals['_DOORBELLSERVICE']._serialized_end=1121
# @@protoc_insertion_point(module_scope)
