# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_stream.proto\x12\nding.video\"\x85\x01\n\nVideoFrame\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x12\n\nvideo_data\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12)\n\nframe_type\x18\x05 \x01(\x0e\x32\x15.ding.video.FrameType\"w\n\x0e\x43ontrolMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12-\n\x0c\x63ontrol_type\x18\x03 \x01(\x0e\x32\x17.ding.video.ControlType\x12\x0f\n\x07message\x18\x04 \x01(\t*2\n\tFrameType\x12\x0b\n\x07I_FRAME\x10\x00\x12\x0b\n\x07P_FRAME\x10\x01\x12\x0b\n\x07\x42_FRAME\x10\x02*p\n\x0b\x43ontrolType\x12\x10\n\x0cJOIN_SESSION\x10\x00\x12\x11\n\rLEAVE_SESSION\x10\x01\x12\x11\n\rSESSION_READY\x10\x02\x12\x0f\n\x0bSESSION_END\x10\x03\x12\r\n\tHEARTBEAT\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x32\xa3\x01\n\x12VideoStreamService\x12?\n\tVideoChat\x12\x16.ding.video.VideoFrame\x1a\x16.ding.video.VideoFrame(\x01\x30\x01\x12L\n\x0eSessionControl\x12\x1a.ding.video.ControlMessage\x1a\x1a.ding.video.ControlMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMETYPE']._serialized_start=291
  _globals['_FRAMETYPE']._serialized_end=341
  _globals['_CONTROLTYPE']._serialized_start=343
  _globals['_CONTROLTYPE']._serialized_end=455
  _globals['_VIDEOFRAME']._serialized_start=35
  _globals['_VIDEOFRAME']._serialized_end=168
  _globals['_CONTROLMESSAGE']._serialized_start=170
  _globals['_CONTROLMESSAGE']._serialized_end=289
  _globals['_VIDEOSTREAMSERVICE']._serialized_start=458
  _globals['_VIDEOSTREAMSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
